import type { Metadata } from "next";
import { Ubuntu } from "next/font/google"; // ✅ Replace Geist with Ubuntu
import "./globals.css";
import StoreProvider from "./StoreProvider";
import ToastProvider from "@/components/common/ToastProvider";
import AppInitializer from "@/components/AppInitializer";

// ✅ Use Ubuntu font with variable
const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust as needed
});

export const metadata: Metadata = {
  title: "Inideg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} antialiased suppressHydrationWarning`}
      >
        <StoreProvider>
          <AppInitializer>{children}</AppInitializer>
        </StoreProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
