import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import ToastProvider from "@/components/common/ToastProvider";
import RouteGuard from "@/components/RouteGuard";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Inideg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} antialiased suppressHydrationWarning `}
      >
        <StoreProvider>
          <RouteGuard>{children}</RouteGuard>
        </StoreProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
